# Generated by Django 5.2.8 on 2025-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('specialty', models.CharField(max_length=100)),
                ('course', models.CharField(help_text="Course (e.g., '2', '3' for students, '0' for coordinators)", max_length=10)),
                ('university_email', models.EmailField(help_text='University email (@stu.sdu.edu.kz)', max_length=254, unique=True)),
                ('personal_email', models.EmailField(blank=True, help_text='Personal email (e.g., @gmail.com)', max_length=254, null=True)),
                ('email', models.EmailField(help_text='Primary email (university_email)', max_length=254, unique=True)),
                ('school', models.CharField(blank=True, help_text='School name (e.g., №35 zhalpy mektep)', max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('access', models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator')], default='student', max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('violation_count', models.IntegerField(default=0)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', help_text='Account status - blocked if 3+ violations', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, help_text='Status (e.g., Coordinator of B block)', max_length=255, null=True)),
                ('degree', models.CharField(blank=True, help_text='Degree (e.g., M2, PhD)', max_length=50, null=True)),
                ('special_room', models.CharField(blank=True, help_text='Special room for coordinator', max_length=20, null=True)),
                ('iin', models.CharField(blank=True, help_text='IIN number', max_length=12, null=True)),
                ('iban', models.CharField(blank=True, help_text='IBAN number', max_length=20, null=True)),
                ('doc_type', models.CharField(blank=True, help_text='Document type', max_length=50, null=True)),
                ('doc_number', models.CharField(blank=True, help_text='Document number', max_length=50, null=True)),
                ('doc_issue_date', models.DateField(blank=True, help_text='Document issue date', null=True)),
                ('local_address', models.TextField(blank=True, help_text='Local Address', null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['student_id'],
            },
        ),
    ]
