# Generated by Django 5.2.8 on 2025-11-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('block', models.CharField(choices=[('A', 'Block A'), ('B', 'Block B')], max_length=1)),
                ('floor', models.IntegerField()),
                ('max_capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Block A = male, Block B = female', max_length=10)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['block', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='students.student')),
            ],
            options={
                'verbose_name': 'Explanation',
                'verbose_name_plural': 'Explanations',
                'db_table': 'explanations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student',), name='one_pending_per_student')],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='explanations.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='students.student')),
            ],
            options={
                'verbose_name': 'Room Assignment',
                'verbose_name_plural': 'Room Assignments',
                'db_table': 'room_assignments',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('student',), name='one_active_room_per_student')],
            },
        ),
    ]
